version: "3.3"

services:
  server:
    build: ./server
    container_name: server
    env_file: .env
    depends_on: 
      - database
    volumes:
      - ./server/:/server
    links:
      - database
    ports:
      - '5001:5001'

  database:
    image: mysql:5.7
    container_name: mysqldb
    command: --init-file /Auth_app/init.sql
    volumes:
        - ./init.sql:/Auth_app/init.sql
    restart: always
    env_file: .env
    ports:
      - '3306:3306'